### ISSUE TITLE
SyntaxError: Unexpected token u in JSON at position 0, when clicking on 'edit' button

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/vuejs-booster#12]
![screenshot from 2018-01-19 15-17-11](https://user-images.githubusercontent.com/6443576/35165139-e5c6b07c-fd2b-11e7-8f27-210d40045ca0.png)

**Comment by deewhyweb** [comment]
I'll take a look at this now.

**Comment by deewhyweb** [comment]
PR Submitted

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/vuejs-booster/pull/13
