### ISSUE TITLE
fix refresh table after remove, add and update

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/vuejs-booster#2]

**Comment by helio-frota** [comment]
working with delete:
https://github.com/helio-frota/vuejs-booster/commit/3ddc0c4e4d176ff0d71484c387a4373c05e73ae4

**Comment by deewhyweb** [comment]
PR Submitted to refresh after add.

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/vuejs-booster/pull/10
https://github.com/bucharest-gold/vuejs-booster/pull/11
