### ISSUE TITLE
http-client: axios, vue-resource, roi...

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/vuejs-booster#6]
Seems vuejs don't have a default http-client and because this I've added [roi](https://github.com/bucharest-gold/roi).

I'm not feeling 100% comfortable with this because seems most of the vuejs users are using 
[axios](https://github.com/axios/axios) or [vue-resource](https://github.com/pagekit/vue-resource).

As a purpose of trying to make things more similar as users do, it might be better to use axios or vue-resource instead of roi.

**Comment by deewhyweb** [comment]
Looks like a good place for me to start, I'll take a look at this issue

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/vuejs-booster/pull/8
